version: '3.7'

services:
  ts-node:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
    container_name: ts-node
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
